import { useState } from 'react';
import { motion } from 'framer-motion';
import { Shield, Key, CheckCircle, XCircle } from 'lucide-react';

export default function TwoFactorSetup() {
  const [qrCode, setQrCode] = useState<string | null>(null);
  const [setupCode, setSetupCode] = useState('');
  const [status, setStatus] = useState<'idle' | 'generating' | 'verifying' | 'success' | 'error'>('idle');
  const [message, setMessage] = useState('');

  const generate2FA = async () => {
    setStatus('generating');
    setMessage('');
    try {
      const token = localStorage.getItem('upahaar_token');
      const response = await fetch(`${process.env.NEXT_PUBLIC_API_URL || 'http://localhost:5000'}/api/auth/2fa/generate`, {
        method: 'POST',
        headers: { 'Authorization': `Bearer ${token}` }
      });
      const data = await response.json();
      if (response.ok && data.qrCode) {
        setQrCode(data.qrCode);
        setStatus('idle');
      } else {
        setStatus('error');
        setMessage(data.message || 'Failed to generate 2FA');
      }
    } catch (err) {
      setStatus('error');
      setMessage('Network error while generating 2FA');
    }
  };

  const verify2FA = async () => {
    if (!setupCode || setupCode.length < 6) {
      setStatus('error');
      setMessage('Please enter a 6-digit code');
      return;
    }
    
    setStatus('verifying');
    setMessage('');
    try {
      const token = localStorage.getItem('upahaar_token');
      const response = await fetch(`${process.env.NEXT_PUBLIC_API_URL || 'http://localhost:5000'}/api/auth/2fa/turn-on`, {
        method: 'POST',
        headers: { 'Authorization': `Bearer ${token}`, 'Content-Type': 'application/json' },
        body: JSON.stringify({ totp_code: setupCode })
      });
      const data = await response.json();
      if (response.ok) {
        setStatus('success');
        setMessage('2-Factor Authentication successfully enabled!');
        setQrCode(null);
      } else {
        setStatus('error');
        setMessage(data.message || 'Invalid code, please try again.');
      }
    } catch (err) {
      setStatus('error');
      setMessage('Network error while verifying 2FA');
    }
  };

  if (status === 'success') {
    return (
      <div className="bg-green-50 border border-green-200 rounded-2xl p-6 text-center">
        <CheckCircle className="w-12 h-12 text-green-500 mx-auto mb-2" />
        <h3 className="text-lg font-bold text-green-800">2FA is Enabled</h3>
        <p className="text-sm text-green-600 mt-1">Your account is highly secure.</p>
      </div>
    );
  }

  return (
    <div className="bg-white rounded-3xl shadow-xl overflow-hidden border border-gray-100">
      <div className="bg-gradient-to-r from-medical-dark to-medical-blue p-6 text-white">
        <div className="flex items-center gap-3 mb-2">
          <Shield className="text-blue-200" size={24} />
          <h2 className="text-xl font-bold">Two-Factor Authentication (2FA)</h2>
        </div>
        <p className="text-sm text-blue-100 opacity-90">Add an extra layer of security using Google Authenticator.</p>
      </div>

      <div className="p-6">
        {!qrCode ? (
          <div className="text-center">
            <p className="text-gray-600 mb-4 text-sm">Once enabled, you will need to enter a 6-digit code from your phone every time you log in.</p>
            <motion.button
              whileHover={{ scale: 1.02 }}
              whileTap={{ scale: 0.98 }}
              onClick={generate2FA}
              disabled={status === 'generating'}
              className="bg-medical-blue text-white px-6 py-3 rounded-xl font-bold shadow-lg shadow-blue-500/30 hover:shadow-blue-500/50 transition-all flex items-center justify-center gap-2 mx-auto w-full max-w-xs"
            >
              <Key size={18} />
              {status === 'generating' ? 'Generating...' : 'Setup Authenticator App'}
            </motion.button>
          </div>
        ) : (
          <div className="space-y-6 text-center animate-in fade-in slide-in-from-bottom-4">
            <p className="text-sm font-semibold text-gray-700">1. Scan this QR code with Google Authenticator or Authy</p>
            
            <div className="bg-gray-50 p-4 rounded-2xl inline-block shadow-inner border border-gray-100">
              <img src={qrCode} alt="2FA QR Code" className="w-48 h-48 mx-auto mix-blend-multiply" />
            </div>

            <div className="space-y-3">
              <p className="text-sm font-semibold text-gray-700">2. Enter the 6-digit code generated by your app</p>
              <input 
                type="text" 
                maxLength={6}
                value={setupCode}
                onChange={(e) => setSetupCode(e.target.value.replace(/\D/g, ''))}
                placeholder="000000"
                className="w-full max-w-xs text-center text-2xl tracking-[0.5em] px-4 py-3 rounded-xl border-2 border-gray-200 focus:border-medical-blue focus:ring-4 focus:ring-medical-blue/20 outline-none transition-all font-mono"
              />
            </div>

            <motion.button
              whileHover={{ scale: 1.02 }}
              whileTap={{ scale: 0.98 }}
              onClick={verify2FA}
              disabled={status === 'verifying' || setupCode.length !== 6}
              className="bg-medical-dark text-white px-6 py-3 rounded-xl font-bold shadow-lg shadow-gray-500/30 hover:shadow-gray-500/50 transition-all w-full max-w-xs mx-auto disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {status === 'verifying' ? 'Verifying...' : 'Verify and Enable'}
            </motion.button>
          </div>
        )}

        {status === 'error' && (
          <div className="mt-4 p-3 bg-red-50 text-red-600 rounded-xl flex items-center gap-2 text-sm justify-center border border-red-100">
            <XCircle size={16} />
            {message}
          </div>
        )}
      </div>
    </div>
  );
}
